export type TaskStatus = 'pending' | 'in_progress' | 'done'

export interface Task {
  id: string
  description: string // max 200 chars
  impact: number // 1-10
  confidence: number // 1-10
  ease: number // 1-10
  status: TaskStatus
  explanation: string // generated by AI or manual
}

export interface GeminiAnalysis {
  impact: number
  confidence: number
  ease: number
  explanation: string
}

export interface ModalState {
  open: boolean
  selectedTask: Task | null
}
