#!/usr/bin/env ts-node

import { execSync } from 'child_process';
import * as path from 'path';
import { Octokit } from '@octokit/rest';

// simple helper to run shell commands and return output
function sh(cmd: string) {
  return execSync(cmd, { stdio: 'pipe' }).toString().trim();
}

async function main() {
  const repoDir = path.resolve(__dirname, '..');
  process.chdir(repoDir);

  // 1. detect current branch
  const currentBranch = sh('git rev-parse --abbrev-ref HEAD');
  console.log('current branch ->', currentBranch);

  // try to extract issue number from branch name (e.g. feature/123-desc)
  const issueMatch = currentBranch.match(/(\d+)/);
  if (issueMatch) {
    console.log('found issue in branch name:', issueMatch[1]);
  }

  // 2. determine next issue from GitHub
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    console.error('set GITHUB_TOKEN environment variable with repo access');
    process.exit(1);
  }

  const octokit = new Octokit({ auth: token });
  const owner = 'your-org-or-user';
  const repo = 'gestor-tareas-ice';

  // list open issues labelled "todo" ordered by created
  const issues = await octokit.issues.listForRepo({
    owner,
    repo,
    state: 'open',
    labels: 'todo',
    sort: 'created',
    direction: 'asc',
    per_page: 10,
  });

  if (issues.data.length === 0) {
    console.log('no open issues with label todo');
    return;
  }

  const nextIssue = issues.data.find(i => !i.pull_request);
  if (!nextIssue) {
    console.log('no suitable issue found');
    return;
  }

  console.log('next issue to work on:', nextIssue.number, nextIssue.title);

  // 3. create new branch
  const branchName = `feature/${nextIssue.number}-${nextIssue.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')}`;
  sh(`git checkout -b ${branchName}`);
  console.log('created and switched to', branchName);

  // 4. generate starter files (this is manual placeholder)
  // for example, create a stub component
  const componentName = `Issue${nextIssue.number}Component`;
  const componentPath = path.join(repoDir, 'src', 'components', `${componentName}.tsx`);
  const componentCode = `import React from 'react';

export const ${componentName}: React.FC = () => {
  return <div>${nextIssue.title}</div>;
};
`;
  require('fs').writeFileSync(componentPath, componentCode);
  console.log('stub component created at', componentPath);

  // 5. run validations
  try {
    sh('npm run lint');
    sh('npm run format');
    sh('npm run build');
    // tests would go here
  } catch (err) {
    console.warn('validation failed, please fix before committing');
  }

  // 6. commit & push
  sh('git add .');
  sh(`git commit -m "feat: start work on #${nextIssue.number} - ${nextIssue.title}"`);
  sh(`git push -u origin ${branchName}`);
  console.log('pushed branch to remote');

  // 7. create pull request
  const pr = await octokit.pulls.create({
    owner,
    repo,
    head: branchName,
    base: 'dev',
    title: `#${nextIssue.number} ${nextIssue.title}`,
    body: `Automated PR generated by generadortareas skill`,
  });
  console.log('pull request created:', pr.data.html_url);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
